### ISSUE TITLE
Support running on Git URL

### ISSUE THREAD

**Issue by itaisteinherz** [stefanjudis/credits-cli#102]
Since the common usecase is running `$ credits` on a cloned git repo, it would be nice if you provide the repo URL to `credits-cli`, and it would analyze the project in the given URL:

```
$ credits https://github.com/stefanjudis/credits-cli.git
-> Credits for credits
...
```

Also, it may be possible to do this without cloning the repo by only fetching `package.json` and analyzing it, but that would be an optional optimization.

**Comment by stefanjudis** [comment]
Hey @itaisteinherz,

this is a great idea but unfortunately, that's not easily doable as of right now. This package relies on [credits](https://github.com/stefanjudis/credits) which scans the locally installed dependencies. 

So while this functionality might be possible this would need a major rewrite. :)

**Comment by itaisteinherz** [comment]
Should I move this issue to `credits` then?

**Comment by stefanjudis** [comment]
Sure. :) 

I'm not sure if I'll have time to implement that, happy to take contributions though. 😊

**Comment by itaisteinherz** [comment]
Moved to stefanjudis/credits#136.
