### ISSUE TITLE
npm linked modules appear to break

### ISSUE THREAD

**Issue by allain** [stefanjudis/credits-cli#17]
With a handful of projects, running credits is simply returning without outputting anything.

The only difference I can see, is that the failing ones have some npm linked packages.

**Comment by stefanjudis** [comment]
Are the projects you're referring to public available, so that I can have a look?

**Comment by allain** [comment]
No, I just happened to have a great mangled mess of npm links for a project I was testing locally. I've found the issue and submitted a pull request on the credits repo that resolves the case when there are cycles in the npm links.

**Comment by stefanjudis** [comment]
Thx. Will have a look tomorrow.

**Comment by allain** [comment]
Cheers. Nice work btw.

**Comment by stefanjudis** [comment]
Thanks again for the PR. This should be solved here,right? :)

**Comment by allain** [comment]
I think it has solved it.

And thanks.
