### ISSUE TITLE
Should we merge?

### ISSUE THREAD

**Issue by bahmutov** [stefanjudis/credits-cli#4]
I am generating list of 3rd party dependencies including descriptions using https://github.com/bahmutov/modules-used - this gives me a list in the markdown form like this

```
* [name](url) - description
* [name 2](url 2) - description 2
```

This I usually pipe it into the README to update a section using https://github.com/bahmutov/update-markdown 

Maybe we could merge credits-cli or at least create a super module with all info about the 3rd party libraries?

**Comment by stefanjudis** [comment]
I think these are still two different use cases.

Yours is presenting modules and `credits` is more about the people. 

But I'm totally into your README piping. :bowtie: 

>  at least create a super module with all info about the 3rd party libraries

Yeah - sounds fun! Let's do it!

**Comment by bahmutov** [comment]
ok, will make a PR to your module at some point. Maybe `--modules` to output a list of modules and `--committers` to output people. And then `--update` to pipe into README or any other markdown

**Comment by stefanjudis** [comment]
> at least create a super module with all info about the 3rd party libraries

wait - I was thinking of this super module to be a wrapper around `credits` and `modules-used`.

About the md functionality I'd prefer to handle it like discussed here:

https://github.com/stefanjudis/credits-cli/issues/6

**Comment by Hypercubed** [comment]
Hello @bahmutov ,

I just updated this tool to glob `node_modules`, `bower_components`, and `jspm_packages`.  It looks like `modules-used` is using `package.json` instead of globbing.  Do you still think there is some common ground here?

**Comment by bahmutov** [comment]
probably not, let us keep everything like it is
