### ISSUE TITLE
Use fancy things provided by node v4.0

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/credits-cli#5]
The lines for concatenating the help of the commands are really ugly.
Extract these into a file and read it.

**Comment by sindresorhus** [comment]
Just target Node.js 4 and use template literals instead.

Reasoning: https://github.com/sindresorhus/ama/issues/250#issuecomment-145645283

Example: https://github.com/sindresorhus/trash-cli/blob/eaec11de91ebadddcfa6353cdccd1547ca34cfa2/cli.js#L7-L13

**Comment by stefanjudis** [comment]
I saw that and decided to not target only node `v4.0`.

The reason for that is, that I've been switching between node version all the time.
And I'm still forced on a few projects to move away from `v4.0` to `v0.12` because in some cases it's still not working properly in projects.

How is your rate on supporting only node `v4.0` - many complains so far?

**Comment by sindresorhus** [comment]
Not much complaint.

Then you need to change: https://github.com/stefanjudis/credits-cli/blob/f36629b9d8777eb75c835e7f7652fdb0422d11f0/package.json#L23

**Comment by stefanjudis** [comment]
Aah touché... :D 

Okay - agree - will go back to `v4.0` then. :+1:
