### ISSUE TITLE
Support several reporters including Markdown

### ISSUE THREAD

**Issue by mischah** [stefanjudis/credits-cli#6]
Would love to have an option for that. :kissing:

**Comment by stefanjudis** [comment]
yeah - Nice!

Any special wishes on the CLI interface? 

Something like `credits . > Creditds.md` might be nice, or?

**Comment by mischah** [comment]
My first idea was to have an option for that.

But 

```
credits . > Creditds.md
```

is way more flexible and sounds perfect to me :+1:

**Comment by stefanjudis** [comment]
I think I'll drop the current `-i` option and will provide something like:

```
credits . 
credits . --reporter extended
credits . --reporter markdown > CREDITS.md
```

**Comment by mischah** [comment]
Hej, that’s awesome. Thank you very much :octocat:

**Comment by stefanjudis** [comment]
:tada: 

Let me know when you push the first `CREDITS.md` files. :)

**Comment by mischah** [comment]
[Done](https://github.com/mischah/itunes-remote/commit/b1088472b85eff8586a94b35204e2d3bcdb10ac2) :kissing_heart:
