### ISSUE TITLE
Support other systems

### ISSUE THREAD

**Issue by Hypercubed** [stefanjudis/credits-cli#9]
I'd like to suggest you support other systems (for lack of a better term) for example JSPM and Bower.  I'm willing to help.  Should we create a `credits` modules for each system or add other systems to the existing lib?

**Comment by stefanjudis** [comment]
I think it makes sense to have it in here.
And implementation shouldn't be that hard. ;)

Can you please provide some first ideas on how to put this into the CLI interface?

**Comment by Hypercubed** [comment]
I put together a hack of `credits` with some basic support for bower and jspm.  See here:  https://github.com/Hypercubed/credits/blob/feature/hack/index.js

I guess a few things need to happen:

1) The export from `credit` needs to accept a `subPath`.  https://github.com/Hypercubed/credits/blob/feature/hack/index.js#L29
2) `readDirectory` needs to look for `package.json` or `bower.json` https://github.com/Hypercubed/credits/blob/feature/hack/index.js#L48
3) I'm guessing we'd want the different systems to be options in the cli.  This would call `credit` multiple times with different paths and `subPath`s.  https://github.com/Hypercubed/credits/blob/feature/hack/index.js#L22
4) Lastly, something I haven't tried yet, is to look for the correct paths in the config files (`.bowerrc` for bower, `package.json` for jspm).

**Comment by stefanjudis** [comment]
Hmm - that gets more complicated than expected. Will have a look into your `hack` soon'ish. :)

**Comment by stefanjudis** [comment]
@Hypercubed 

Let's move the discussion over to the actual module.

Only thing to be discussed here should be how we build up the cli interface.

I'm thinking of something like:

```
Usage
  $ credits <path>
Options
  -r, --reporter 
  -p, --package-manager Define package manager to look for
Examples
  $ credits /projects/foo
  $ credits /projects/foo --p=npm,bower
```

But I think I'd actually default to everything that we can find, which would mean `npm`, `bower` & `jspm`.

**Comment by Hypercubed** [comment]
Done with v3
